### ISSUE TITLE
[ Feature Request] Conversion of video format to GIF Format

### ISSUE THREAD

**Issue by sanjaybaskaran01** [75lb/handbrake-js#73]

**Comment by 75lb** [comment]
Hi, I'm afraid that is beyond the scope of handbrake-js.. This module simply wraps the underlying [`HandbrakeCLI`](https://handbrake.fr/) command line tool - you should direct encoding requests to that project. 

As a general rule, if it is supported by `HandbrakeCLI` then it should be supported by handbrake-js. If `HandbrakeCLI` can create a GIF then this module will be able to also (because it wraps Handbrake).
